#webconfig:
#  baseUrl: http://localhost:8080
#  externalApiKey: 	898503cde7f033277be0c60d4fea605a153db02bac8116c7ceafc34ef9838ac8
#  externalApiUrl: https://www.reed.co.uk/api/1.0/search

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_database?serverTimezone=UTC
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    hu.progmasters: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
